from setuptools import setup, find_packages

setup(name='pythalesians',
      version='0.1a',
      description='Financial analysis library in Python to backtest trading strategies with plotting',
      maintainer='Thalesians Ltd, Saeed Amen',
      maintainer_email='saeed@thalesians.com',
      author='Thalesians Ltd, Saeed Amen',
      author_email='saeed@thalesians.com',
      license='Apache 2.0',
      keywords = ['pandas', 'bloomberg', 'plot', 'finance', 'fx'],
      url = 'https://github.com/thalesians/pythalesians',
      packages = find_packages(),
      include_package_data = True,
      install_requires = ['pandas',
                          'matplotlib',
                          'twython',
                          'pytz',
                          'requests',
                          'numpy'],
      extra_requires = ['pyfolio',
                        'bcolz'],
	  zip_safe=False)